apiVersion: v1
kind: Service
metadata:
  name: statuspage-service
  labels:
    app: statuspage           # Ensure the label matches the selector in the ServiceMonitor
spec:
  type: NodePort
  selector:
    app: statuspage           # Ensure this matches the app label in the Deployment
  ports:
    - name: http-metrics       
      port: 8001               
      targetPort: 8001 
